version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "@prisma/adapter-pg"
      - dependency-name: "@prisma/client"
      - dependency-name: "prisma"
